config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  resources :rooms, only: %i[index show] do
    resources :messages, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  validates :body, presence: true, length: { maximum: 100 }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  validates :name, presence: true
  validates :image_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/messages_controller.rb
require 'utils/aws_util'
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    audio_filename = "#{SecureRandom.uuid}.mp3"
    @message.audio_file_name = audio_filename
    if @message.save
      util = AwsUtil.new
      audio = util.text_to_speech_with_polly(@message.body)
      util.s3_upload(audio, audio_filename)
      redirect_to room_path(@message.room), success: '投稿しました'
    else
      redirect_to room_path(@message.room), danger: 'メッセージは100文字以内で投稿してください'
    end
  end

  private

  def message_params
    params.require(:message).permit(:body).merge(room_id: params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @message = Message.new
    @messages = Message.where(room_id: params[:id]).order(created_at: :desc)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S0GF0E7V8K"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S0GF0E7V8K');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polly Sample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/3ee7ba73c2.js" crossorigin="anonymous"></script>
    <%= favicon_link_tag('favicon.ico') %>
    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="row mb-3 justify-content-center text-center">
  <div class="col-lg-4">
  <%= render 'shared/flash_message' %>
    <%= form_with model: [room, message], id: 'new_message' do |f| %>
      <%= f.text_area :body, class: 'form-control mb-3', placeholder: 'メッセージ（100文字まで）' %>
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="container">
  <div class="row align-items-center border-bottom">
    <div class="text-end my-3" style="width:4rem;">
      <button
        id="js-audio-button"
        type="button"
        class="btn btn-outline-secondary rounded-circle p-0"
        style="width:3rem;height:3rem;"
        data-audio-url="<%= ENV['CLOUDFRONT_BASE_URL'] + message.audio_file_name %>"
      >
        <i class="fas fa-play text-dark"></i>
      </button>
    </div>
    <div class="col-9 my-3">
      <h3 class="text-left mb-0">
        <%= message.body %>
      </h3>
    </div>
  </div>
</div>

app/views/rooms/_room.html.erb
<div class="card col-md-3 mx-3 mb-3">
  <%= image_tag room.image_name, class: 'card-img-top', size: :auto %>
  <div class="card-body text-center">
    <h4 class="card-title">
      <%= room.name %>
    </h4>
    <%= link_to '入室する', room, class:'btn btn-primary' %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <%= render @rooms %>
  </div>
</div>

app/views/rooms/show.html.erb
<%= link_to "部屋選択に戻る", rooms_path, class: "btn btn-primary text-left" %>
<div class="container">
  <br>
  <%= image_tag @room.image_name, size: :auto, class: 'd-block mx-auto'%>
  <h3 class="text-center">
    <%= @room.name %>
  </h3>
  <%= render 'messages/form', { room: @room, message: @message } %>
  <h3 class="text-center mb-3"><u>メッセージ</u></h3>
  <%= render @messages, partial: 'messages/_message' %>
</div>
<%= javascript_pack_tag 'audio' %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/static_pages/top.html.erb
<div class="container">
  <div class='text-center'>
    <div class='mb-3'>Amazon Pollyサンプル</div>
    <div class='mb-3'>Amazon Pollyを利用してメッセージを<br>音声化するアプリのサンプルです。</div>
    <%= link_to "部屋選択へ進む", rooms_path, class: "btn btn-primary" %>
  </div>
</div>